---
# tasks specific to Ubuntu
- name: Install necessary packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - gcc
    - git
    - python3-dev
    - python3-pip
    - sudo
    - wget
