---
# tasks specific to Ubuntu
- name: Install necessary packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - gcc
    - git
    - module-init-tools
    - python-dev
    - python-pip
    - sudo
    - wget

