---
# tasks for Centos 7
  - name: Install epel-elease
    yum: name=epel-release state=latest update_cache=yes

  - name: Install necessary packages
    yum: name={{ item }} state=latest update_cache=yes
    with_items:
      - gcc
      - git
      - kernel-devel
      - python-devel
      - python-pip
      - sudo
      - wget
